### ISSUE TITLE
ImportError on Python < 3.11 — 'from datetime import UTC' is 3.11+

### ISSUE THREAD

**Issue by OmerYasirOnal** [OmerYasirOnal/claudewatch#26]
**Symptom:** \`from datetime import UTC\` raises \`ImportError\` on Python 3.9/3.10. macOS ships with bundled Python 3.9 at \`/Applications/Xcode.app/.../python3\` — if a user installs via that interpreter, the package fails at import time before any pytest/CI catches it.

**Where:** Introduced by PR #20 (conversation_log), and copied to:
- \`backend/detectors/conversation_log.py:6\`
- \`backend/state.py:5\` (added in PR #19)
- \`backend/models.py\`, \`tests/test_current_task.py\`, \`tests/test_linker.py\`, etc. (ruff UP017 cleanup)

**Repro:**
\`\`\`
/usr/bin/python3 -c "from backend.detectors.conversation_log import parse_log"
ImportError: cannot import name 'UTC' from 'datetime'
\`\`\`

**Fix:**
- Revert to \`from datetime import datetime, timezone\` + \`timezone.utc\` everywhere. Slightly more verbose but works on 3.9+.
- Add \`UP017\` to ruff ignore list so it doesn't get re-introduced.
- Add Python 3.10 to the CI matrix to surface this earlier (pyproject says \`>= 3.11\` but lots of macOS users get 3.9 by accident).
